## 1. 코드 재활용을 위한 아발로니 파일 실행시키기

In [1]:
%run ../chap01/abalone.ipynb

## 2. 메인 함수 정의

In [2]:
def steel_exec(epoch_count=10, mb_size=10, report=1):
    load_steel_datast()
    init_model()
    train_and_test(epoch_count, mb_size, report)

## 3. 데이터 적재 함수 정의

In [3]:
def load_steel_dataset():
    with open('../../data/chap03/faults.csv') as csvfile:
        csvreader = csv.reader(csvfile)
        next(csvreader, None)
        rows = []
        for row in csvreader:
            rows.append(row)
    global data, input_cnt, output_cnt
    input_cnt, output_cnt = 27, 7
    data = np.asarray(rows, dtype='float32')

## 4. 후처리 과정에 대한 순전파와 역전파 함수의 재정의

In [5]:
def forward_postproc(output, y):
    entropy = softmax_cross_entropy_with_logits(y, output)
    loss = np.mean(entropy)
    return loss, [y, output, entropy]

def backprop_postproc(G_loss, aux):
    y, output, entropy = aux
    
    g_loss_entropy = 1.0 / np.prod(entropy.shape)
    g_entropy_output = softmax_cross_entropy_with_logits_derv(y, output)
    
    G_entropy = g_loss_entropy * G_loss
    G_output = g_entropy_output * G_entropy
    
    return G_output

## 5. 정확도 계산 함수의 재정의

In [6]:
def eval_accuracy(output, y):
    estimate = np.argmax(output, axis=1)
    answer = np.argmax(y, axis = 1)
    correct = np.equal(estimate, answer)
    
    return np.mean(correct)

## 6. 소프트맥스 관련 함수 정의

In [ ]:
def softmax(x): # (N : 미니배치 크기(10), M : 출력벡터 크기(7))
    max_elem = np.max(x, axis = 1) # 안전한 계산을 위해 최대항을 골라냄, (N, )
    diff = (x.transpose() - max_elem).transpose() 
    """
    max_elem의 결과가 (N, ) 크기이고 행렬에서 벡터를 뺄 때는 넘파이 패키지가 행렬의 각 행에 대해 계산을 반복하는데,
    여기에서는 각 열에 대한 반복 감산이 필요하기 때문에
    transpose()함수를 이용해 행렬의 행과 열을 바꾸어 계산을 수행한 후 다시 원상 복귀 처리를 함, 밑에 지수 함수 처리도 마찬가지
    """
    exp = np.exp(diff)
    sum_exp = np.sum(exp, axis =1)
    probs = (exp.transpose() / sum_exp).transpose()
    return probs

def softmax_derv(x, y):
    mb_size, nom_size = 

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([0,1,2])
print(a - b)

[[1 1 1]
 [4 4 4]]


In [23]:
a = np.array([[1, 2], [2, 3], [3, 4]])
b = np.max(a, axis = 1)
c = a.transpose()-b
print('a.t: \n', a.transpose())
print('np.max(a, axis = 1): \n', b)
print('a.transpose() - np.max(a, axis = 1) \n', c)
print('(a.transpose()-b).T \n', c.transpose())

a.t: 
 [[1 2 3]
 [2 3 4]]
np.max(a, axis = 1): 
 [2 3 4]
a.transpose() - np.max(a, axis = 1) 
 [[-1 -1 -1]
 [ 0  0  0]]
(a.transpose()-b).T 
 [[-1  0]
 [-1  0]
 [-1  0]]


In [29]:
a , np.max(a, axis= 1), a.transpose()

(array([[1, 2],
        [2, 3],
        [3, 4]]),
 array([2, 3, 4]),
 array([[1, 2, 3],
        [2, 3, 4]]))

In [18]:
print(a - b)

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 